version: '3.6'
services:
  db:
    image: 'postgres:11'
    container_name: 'tax_postgres'
    ports:
      - '54320:5432'
    volumes:
      - .:/var/lib/postgresql/data
  server:
    build: 
        context: .
        dockerfile: DockerFile
    container_name: 'tax-api'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app