FROM node:10-alpine

RUN mkdir -p /usr/src/tax-api
WORKDIR /usr/srctax-api
RUN npm install  -g nodemon
RUN npm install -g node-gyp
COPY package.json /usr/src/tax-api/package.json
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*


EXPOSE 3000
CMD [ "npm", "run", "dev" ]
